from odoo import api, fields, models, _
from odoo.osv import expression


class ResCompany(models.Model):
    _inherit = 'res.company'

    circular_code = fields.Char(string='Circular Code')

    def _filter_vietnam_coa(self):
        """
        Filter the companies having Vietnam CoA (TT200 / TT133) in self
        """
        if not self:
            return self.env['res.company']
        vn_coa = self.env['account.chart.template']._get_installed_vietnam_coa_templates()
        return self.filtered(lambda company: company.chart_template in vn_coa)

    def _get_account_to_deprecated(self):
        return (
            'chart132', 'chart9993', 'chart9994'
        )

    @api.model
    def _get_vn_account_to_fix(self):
        return {
            'income_financial': ['515'],
            'income_deduction': ['521'],
            'asset_current': ['1381'],
            'liability_current': ['3381'],
        }

    def _fix_accounts_type(self, fixed_type_code_map=None):
        fixed_type_code_map = fixed_type_code_map or {}
        for correct_account_type, account_codes in fixed_type_code_map.items():
            domain = expression.AND([
                [('company_id', 'in', self.ids),
                ('account_type', '!=', correct_account_type)],
                expression.OR([
                    [('code', '=like', f'{code}%')]
                    for code in account_codes
                ]),
            ])
            accounts = self.env['account.account'].search(domain)
            accounts.write({
                'account_type': correct_account_type
            })

    def _fix_vietnam_coa(self):
        """This method is safe for calling multiple times.
        It may take long time for the first run, depending on how large the number of affected journal items is.
        The second time and on may cost a few seconds only.
        """
        if not self.ids:
            return
        vnchart_companies = self._filter_vietnam_coa()
        if vnchart_companies:
            # make sure existing accounts that match the new account template to have correct external ID
            # For example, the account 111 is not available in `l10n_vn` and provided by `l10n_vn_viin`
            # but there is an account 111 created by user before installing `l10n_vn_viin`, hence, may not or may have
            # external id different than the one provided by `l10n_vn_viin`. Hence, error will raise during
            # another 111 account generated by `l10n_vn_viin`
            vnchart_companies._fix_account_account_external_id()

        self.env['account.journal'].flush_model(['type', 'profit_account_id', 'loss_account_id'])
        self._cr.execute("""
            SELECT journal.id
              FROM account_journal journal
            WHERE journal.type IN %(journal_type)s
               AND journal.company_id IN %(company)s
        """, {'journal_type': ('cash', 'bank'), 'company': tuple(self.ids)})
        journal_ids = self._cr.fetchall()
        # Get journals is bank and cash
        journals_to_fix = self.env['account.journal'].browse([j[0] for j in journal_ids])

        self.env['account.account'].flush_model(['tag_ids'])
        self._cr.execute('''
            SELECT acc.id
              FROM account_account acc
              LEFT JOIN account_account_account_tag as tag_ref ON acc.id = tag_ref.account_account_id
            WHERE tag_ref.account_account_id IS NULL
               AND acc.company_id IN %s
        ''', [tuple(self.ids)])
        account_ids = self._cr.fetchall()
        # Get accounts that have no tag
        accounts_to_fix = self.env['account.account'].browse([a[0] for a in account_ids])

        all_accounts = self.env['account.account'].search([
            ('company_id', 'in', self.ids),
            ('code', 'in', ('711', '811', '132', '131', '1131')),
            ('company_id', 'in', vnchart_companies.ids)
            ])

        for r in vnchart_companies:
            # Replace profit account and loss account in cash journal
            # In Cash Journal:
            #     Profit Account: 999* Cash Difference Gain => 711 Other Income
            #     Loss Account: 999* Cash Difference Loss => 811 Other Expenses
            for journal in journals_to_fix.filtered(lambda j: j.company_id == r):
                journal_vals = {}
                income_other_account = all_accounts.filtered(lambda acc: acc.company_id == r and acc.code == '711')
                expense_other_account = all_accounts.filtered(lambda acc: acc.company_id == r and acc.code == '811')
                if income_other_account:
                    journal_vals.update({
                        'profit_account_id': income_other_account.id,
                    })
                if expense_other_account:
                    journal_vals.update({
                        'loss_account_id': expense_other_account.id,
                    })
                if journal_vals.get('profit_account_id', False) and journal_vals.get('loss_account_id', False):
                    journal.write(journal_vals)

            # Cash transit account is type asset_cash
            cash_transit_account = all_accounts.filtered(lambda acc: acc.company_id == r and acc.code == '1131' and acc.account_type != 'asset_cash')
            cash_transit_account.write({
                'name': _('Vietnam Dong'),
                'account_type': 'asset_cash',
                'reconcile': False,
            })

            # Fill account tag for accounts that have no tag
            no_tag_accounts = accounts_to_fix.filtered(lambda acc: acc.company_id == r)
            if no_tag_accounts:
                no_tag_accounts._fill_account_tag_for_vn_coa()

            # Deprecat account 999
            account_journal_early_pay_discount_loss_account_id = r.account_journal_early_pay_discount_loss_account_id
            if account_journal_early_pay_discount_loss_account_id and \
                account_journal_early_pay_discount_loss_account_id.get_external_id().get(account_journal_early_pay_discount_loss_account_id.id) == f'account.{r.id}_chart9993':
                r.account_journal_early_pay_discount_loss_account_id = self.env['account.account'].search([('company_id', '=', r.id), ('code', '=', '635')])
            account_journal_early_pay_discount_gain_account_id = r.account_journal_early_pay_discount_gain_account_id
            if account_journal_early_pay_discount_gain_account_id and \
                account_journal_early_pay_discount_gain_account_id.get_external_id().get(account_journal_early_pay_discount_gain_account_id.id) == f'account.{r.id}_chart9994':
                r.account_journal_early_pay_discount_gain_account_id = self.env['account.account'].search([('company_id', '=', r.id), ('code', '=', '515')])

            # Deprecat account 132, 999*
            xml_ids = [f'account.{r.id}_{account}' for account in self._get_account_to_deprecated()]
            accounts_to_deprecated = self.env['account.account']
            for xml in xml_ids:
                account = self.env.ref(xml, raise_if_not_found=False)
                if account:
                    accounts_to_deprecated |= account

            if accounts_to_deprecated:
                accounts_to_deprecated.deprecated = True
        self._fix_accounts_type(self._get_vn_account_to_fix())

    def _prepare_account_for_company_map_code(self):
        res = super(ResCompany, self)._prepare_account_for_company_map_code()
        if self._filter_vietnam_coa():
            res.update({
                'vat_ctp_account_id': '1331',
                'account_default_pos_receivable_account_id': '1388',
                'default_cash_difference_income_account_id': '711',
                'default_cash_difference_expense_account_id': '811',
                'property_stock_account_input_categ_id': '151',
                'property_stock_account_output_categ_id': '632',
                'property_stock_valuation_account_id': '1561',
                'property_account_other_receivable_id': '1388',
                'property_account_other_payable_id': '3388',
                'property_borrowing_account_id': '3411',
                'advance_account_id': '141',
                'currency_conversion_diff_income_account_id': '711',
                'currency_conversion_diff_expense_account_id': '811',
                'import_vat_ctp_account_id': '1331',
                'export_vat_ctp_account_id': '1331',
                'account_journal_early_pay_discount_loss_account_id': '635',
                'account_journal_early_pay_discount_gain_account_id': '515',
                'property_account_income_refund_categ_id': '5212',
                'general_employee_payable_account_id': '3341',
                'property_lending_account_id': '1283',
            })
        return res

    def _update_show_both_dr_and_cr_trial_balance_vas(self):
        """
        Update show_both_dr_and_cr_trial_balance for accounts according to VAS.
        See help string of show_both_dr_and_cr_trial_balance of accoun.account for more information
        """
        vn_charts = self.env['account.chart.template']._get_installed_vietnam_coa_templates()
        companies = self.with_context(active_test=False).search([('chart_template', 'in', vn_charts)])
        domain = expression.AND([
                [('company_id', 'in', companies.ids)],
                [
                    '|', '|', '|', '|', '|', '|',
                    ('code', '=like', '131%'),
                    ('code', '=like', '138%'),
                    ('code', '=like', '331%'),
                    ('code', '=like', '333%'),
                    ('code', '=like', '334%'),
                    ('code', '=like', '338%'),
                    ('code', '=like', '421%')
                ]
        ])
        accounts = self.env['account.account'].search(domain)
        accounts.write({'show_both_dr_and_cr_trial_balance': True})
