{
    'name': 'Syndicate Revenue Distribution',
    'version': '17.0.1.0.3',
    'summary': 'Revenue distribution by percentages for syndicates',
    'category': 'Accounting',
    'author': 'Custom',
    'license': 'LGPL-3',
    'depends': [
        'account',
        'product',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/company_security.xml',
        'data/sequence.xml',
        'views/fund_box_views.xml',
        'views/revenue_distribution_template_views.xml',
        'views/product_template_views.xml',
        'views/account_move_views.xml',
        'wizard/revenue_distribution_analysis_wizard_views.xml',
        'wizard/revenue_distribution_report_wizard_views.xml',
        'views/revenue_distribution_ledger_views.xml',
        'wizard/revenue_dashboard_wizard_views.xml',
        'wizard/revenue_analytics_wizard_views.xml',
        'report/revenue_analytics_report.xml',
    ],
    'installable': True,
    'application': False,
}
